# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_auto_20160629_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridge',
            old_name='user_id',
            new_name='user',
        ),
    ]
