# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0005_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='save',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='save',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='food_name',
        ),
        migrations.AlterField(
            model_name='fridge',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.User'),
        ),
        migrations.DeleteModel(
            name='Save',
        ),
        migrations.AddField(
            model_name='fridge',
            name='food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge_app.Food'),
        ),
    ]
