# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_auto_20160627_2106'),
        ('log_app', '0002_auto_20160627_1956'),
    ]

    operations = [
    ]
