# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
