# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_auto_20160630_2156'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
